openrewrite.maven.plugin.version = ${openrewrite.maven.plugin.version}
jenkins.parent.version = 6.2189.v695a_c41f5249
bom.version = 6607.v3ed3d8ddfed8
bom.recommended.version = 6607.v3ed3d8ddfed8
remediation.jenkins.plugin.parent.version = 2.37
jenkins.core.minimum.version = ${jenkins.core.minimum.version}
asm-api.version = 9.10.1-216.va_9256d3b_844b_
byte-buddy-api.version = 1.18.10-242.v2fd6300b_db_2b_
commons-lang3-api.version = 3.20.0-109.ve43756e2d2b_4
commons-text-api.version = 1.15.0-218.va_61573470393
commons-compress-api.version = 1.28.0-82.v4df6c060eb_66
gson-api.version = 2.14.0-201.v8eefe5515533
jsoup.version = 1.22.2-95.vc5d00f1eb_42d
joda-time-api.version = 2.14.2-193.v422b_efce56e0
json-api.version = 20260522-217.v0b_18b_8cd4672
json-path-api.version = 3.0.0-218.vcd4dd1355de2
jenkins-test-harness.version = 2573.vd91b_8a_43e019
wiremock.version = 3.13.0
git-changelist-maven-extension.version = 1.13
maven.modernizer.version = ${maven.modernizer.version}
