name: Generate Migration Reports

on:
  workflow_call:

jobs:
  generate-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: pip install pandas

      - name: Download generate_reports.py script
        run: |
          mkdir -p scripts
          curl -sSL https://raw.githubusercontent.com/jenkins-infra/plugin-modernizer-tool/main/scripts/generate_reports.py -o scripts/generate_reports.py

      - name: Generate report script
        run: python scripts/generate_reports.py

      - name: Commit reports and make PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BRANCH_NAME="automation/reports"
          git checkout -b "$BRANCH_NAME"
          git add --all ":!scripts"
          git commit -m "Update modernization reports" || echo "No changes to commit"
          git push origin "$BRANCH_NAME" --force
          gh pr create --title "chore(reports): update plugin migration reports" \
             --body "This PR automatically updates the per-plugin failed migrations and summary report based on the latest metadata files." \
             --head "$BRANCH_NAME" \
             --base main || \
          gh pr edit "$BRANCH_NAME" \
           --title "chore(reports): update plugin migration reports" \
           --body "This PR automatically updates the per-plugin failed migrations and summary report based on the latest metadata files."
